server:
  port: 8080 
  prefix: /hehe
assets:
  chrome: 
    widnows: C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe
    linux: chromium-browser
    mac: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  root: ./assets/
  page:
    pay: pay.html
    video: video.html